package fr.example.entity;

import java.io.Serializable;

import fr.example.annotation.Experimental;
import fr.example.util.ExpirationPredicate;
import jakarta.persistence.*;
import lombok.Data;
import lombok.ToString;

/**
 * Note: auto-generated by jpa-entity-generator
 * TODO: This A/B testing mechanism is no longer used
 */
@Data
@ToString
@Deprecated
@Entity(name = "com.example.entity.ABTest")
@Table(name = "abtest")
public class ABTest implements Serializable, ExpirationPredicate {

  @Id
  @Column(name = "\"identifier\"", nullable = false, length = 50)
  private String identifier;
  @Column(name = "\"expiration_timestamp\"", nullable = false)
  private Integer expirationTimestamp;
  @Experimental(comment = "The expected data format is JSON")
  @Column(name = "\"config\"", nullable = true, length = 2147483647)
  private String config;
}
